apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
spec:
  storageClassName: "storage"
  capacity:
    storage: 250G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pv-claim-demo
  gcePersistentDisk:
    pdName: phoneme-6-2021-01-06
    fsType: ext4
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-demo
spec:
  storageClassName: "storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250G
