apiVersion: v1
kind: Pod
metadata:
  name: demo-train-pod
spec:
  containers:
  - image: drz1/pod-stats-gpu-dir_2021-03-17
    name: test-container
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
    #command: ["sudo", "date"] #["while", "True;", "do", "echo", "hello;", "sleep 1;", "done;"]
    volumeMounts:
    - mountPath: /mnt/disks/data_disk/
      name: test-volume
  volumes:
  - name: test-volume
    # This GCE PD must already exist.
    gcePersistentDisk:
      pdName: k8s-master-disk-2021-03-01
      fsType: ext4
  nodeSelector:
    cloud.google.com/gke-nodepool: gpu-pool
  #restartPolicy: Never
  #imagePullSecrets:
  #- name: regcred

