apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - image: drz1/train_update_2021-03-24
    name: test-container
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /mnt/disks/data_disk/
      name: test-volume
  volumes:
  - name: test-volume
    # This GCE PD must already exist.
    gcePersistentDisk:
      pdName: k8s-train-disk-2021-03-01
      fsType: ext4
  nodeSelector:
    cloud.google.com/gke-nodepool: gpu-pool
  #restartPolicy: Never
  #imagePullSecrets:
  #- name: regcred

