apiVersion: v1
kind: Pod
metadata:
  name: speech-demo
spec:
  containers:
    - name: deepspeech
      image: gcr.io/speak-ml-dev/speak-train_2021-02-19
      #resources:
      #  requests:
      #    ephemeral-storage: 100M
      #  limits:
      #    nvidia.com/gpu: 1
      volumeMounts:
      #- mountPath: "/var/www/html"
      #  name: pvc-demo-volume
      - mountPath: "/mnt/disks/data_disk/"
        name: pv-data
        readOnly: true
  volumes:
    #- name: pvc-demo-volume
    #  persistentVolumeClaim:
    #    claimName: hello-web-disk
    - name: pv-data
      gcePersistentDisk:
        pdName: k8s-master-disk-2021-03-01
        fsType: ext4
  nodeSelector:
    gpu: "true"
    #cloud.google.com/gke-nodepool: gpu-pool
