apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-data
#    namespace: elastic-job
spec:
#    storageClassName: "storage"
    capacity:
        storage: 2000Gi
    accessModes:
        - ReadOnlyMany
    gcePersistentDisk:
        pdName: data-disk-ssd-2021-01-06
        fsType: ext4
    claimRef:
#        namespace: elastic-job
        name: pv-claim-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pv-claim-data
#    namespace: elastic-job
spec:
#    storageClassName: "storage"
    accessModes:
        - ReadOnlyMany
    resources:
        requests:
            storage: 2000Gi
