apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage
  #namespace: elastic-job
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
provisioner: pd.csi.storage.gke.io

