apiVersion: elastic.pytorch.org/v1alpha1
kind: ElasticJob
metadata:
  name: deepspeech
  namespace: elastic-job
spec:
  # Use "etcd-service:2379" if you already apply etcd.yaml
  rdzvEndpoint: "etcd-service:2379"
  minReplicas: 1
  maxReplicas: 1
  replicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: ExitCode
      template:
        apiVersion: v1
        kind: Pod
        spec:
          containers:
            - name: deepspeech
              image: drz1/train_no-cmd_2021-03-23
              imagePullPolicy: Always
              command: ["python", "-m", "torchelastic.distributed.launch"]
              args:
                - "--nproc_per_node=1"
                - "--nnodes=1" 
                - "train.py"
                - "configs/ctc_config_ph0.yaml"
              resources:
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
                - mountPath: "/mnt/disks/data_disk/"
                  name: vol-data
                  #readOnly: true
          volumes:
            - name: vol-data
              gcePersistentDisk:
                pdName: k8s-master-disk-2021-03-01
                fsType: ext4
              #persistentVolumeClaim:
              #  claimName: pv-claim-data
              #  readOnly: true
          nodeSelector:
            cloud.google.com/gke-nodepool: gpu-pool
