apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hwd
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    name: pvc-hwd
  gcePersistentDisk:
    pdName: test-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hwd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
